force-app/main/default/objects/Demo_Setup_Recruit_Question__c/Demo_Setup_Recruit_Question__c.object-meta.xml
<CustomObject>
    <label>Demo Setup Recruit Question</label>
    <nameField>
        <label>Demo Setup Recruit Questions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demo Setup Recruit Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Setup_Recruit_Question__c/fields/Default_Answer__c.field-meta.xml
<CustomField>
    <fullName>Default_Answer__c</fullName>
    <label>Default Answer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Setup_Recruit_Question__c/fields/Default_Answer_Score__c.field-meta.xml
<CustomField>
    <fullName>Default_Answer_Score__c</fullName>
    <description>This value is used to score the question in the one-click flow to create the recruit (not the recruit lead form)</description>
    <inlineHelpText>This value is used to score the question in the one-click flow to create the recruit (not the recruit lead form)</inlineHelpText>
    <label>Default Answer Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demo_Setup_Recruit_Question__c/fields/Demo_Setup_Name__c.field-meta.xml
<CustomField>
    <fullName>Demo_Setup_Name__c</fullName>
    <label>Demo Setup Name</label>
    <referenceTo>Demo_Setup__c</referenceTo>
    <relationshipLabel>Demo Setup Recruit Questions</relationshipLabel>
    <relationshipName>Demo_Setup_Recruit_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demo_Setup_Recruit_Question__c/fields/Demo_Setup_Recruit_Answer_s__c.field-meta.xml
<CustomField>
    <fullName>Demo_Setup_Recruit_Answer_s__c</fullName>
    <inlineHelpText>Enter a comma separated list of values (Yes, No, Maybe) for the recruit to select from.</inlineHelpText>
    <label>Demo Setup Recruit Answer(s)</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/eeFlowRecruitQuestionFormHelper.cls
public with sharing class eeFlowRecruitQuestionFormHelper {


    @AuraEnabled
    public static List<Demo_Setup_Recruit_Question__c> getRecruitQuestions(String demoSetupId) {
        System.debug('Running eeFlowRecruitQuestionFormHelper getRecruitQuestions');
        System.debug('demoSetupId = "' + demoSetupId + '"');   

        return [SELECT Id, Default_Answer__c, Name, Demo_Setup_Recruit_Answer_s__c, Default_Answer_Score__c, Order__c FROM Demo_Setup_Recruit_Question__c WHERE Demo_Setup_Name__c = :demoSetupId ORDER BY Order__c ASC];
     }

}